version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "26.2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gradle-26-1-2:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "26.2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions-26-1-2:
        patterns:
          - "*"