org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
kotlin.daemon.jvmargs=-Xmx2G
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.19
fabric_kotlin_version=1.13.13+kotlin.2.4.10
mod_version=1.2.4
maven_group=com.github.noamm9
mod_name=NoammAddons
modmenu_version=18.0.0
fabric_version=0.155.2+26.1.2
ktor_version=3.5.2
universalcraft_version=516