package com.github.noamm9.ui.utils

import org.lwjgl.glfw.GLFW

enum class ResizeCorner(val cursor: Int) {
    NONE(GLFW.GLFW_ARROW_CURSOR),
    LEFT(GLFW.GLFW_HRESIZE_CURSOR),
    RIGHT(GLFW.GLFW_HRESIZE_CURSOR),
    TOP(GLFW.GLFW_VRESIZE_CURSOR),
    BOTTOM(GLFW.GLFW_VRESIZE_CURSOR),
    TOP_LEFT(GLFW.GLFW_RESIZE_NWSE_CURSOR),
    TOP_RIGHT(GLFW.GLFW_RESIZE_NESW_CURSOR),
    BOTTOM_LEFT(GLFW.GLFW_RESIZE_NESW_CURSOR),
    BOTTOM_RIGHT(GLFW.GLFW_RESIZE_NWSE_CURSOR);
}