package com.github.noamm9.utils.location

enum class WorldType(val tabName: String) {
    BackwaterBayou("Backwater Bayou"),
    Catacombs("Catacombs"),
    CrimsonIsle("Crimson Isle"),
    CrystalHollows("Crystal Hollows"),
    DarkAuction("Dark Auction"),
    DeepCaverns("Deep Caverns"),
    DungeonHub("Dungeon Hub"),
    DwarvenMines("Dwarven Mines"),
    End("The End"),
    Galatea("Galatea"),
    Garden("Garden"),
    GoldMine("Gold Mine"),
    Home("Private Island"),
    Hub("Hub"),
    JerryWorkshop("Jerry's Workshop"),
    Kuudra("Kuudra"),
    Mineshaft("Mineshaft"),
    Park("The Park"),
    Rift("The Rift"),
    SpiderDen("Spider"),
    LotusAtoll("Lotus Atoll"),
    PrivateIslandGuest("Private Island Guest"),
    GardenGuest("Garden Guest"),
    TorrhusCanyon("Torrhus Canyon"),
    Safari("Safari"),
    TheBarn("The Farming Islands");
}