package com.github.noamm9.utils

import com.github.noamm9.NoammAddons
import com.github.noamm9.NoammAddons.mc
import net.minecraft.client.resources.sounds.SoundInstance
import net.minecraft.client.sounds.JOrbisAudioStream
import net.minecraft.core.Holder
import net.minecraft.resources.Identifier
import net.minecraft.sounds.SoundEvent
import org.lwjgl.openal.AL10
import java.io.InputStream
import java.nio.file.Files
import java.nio.file.Paths
import kotlin.concurrent.thread

object SoundUtils {
    private val SOUNDS_DIR = Paths.get("config", NoammAddons.MOD_NAME, "sounds")

    fun playEvent(event: Holder.Reference<SoundEvent>, volume: Float = 1.0f, pitch: Float = 1f) {
        playEvent(event.value(), volume, pitch)
    }

    fun playEvent(event: SoundEvent, volume: Float = 1.0f, pitch: Float = 1f) {
        val weightedSoundSet = mc.soundManager.getSoundEvent(event.location) ?: return
        val sound = weightedSoundSet.getSound(SoundInstance.createUnseededRandom())
        val soundLocation = sound.location
        val actualPath = "sounds/${soundLocation.path}.ogg"
        val fileLocation = Identifier.fromNamespaceAndPath(soundLocation.namespace, actualPath)
        playInternal(fileLocation, volume, pitch)
    }

    fun playExternal(fileName: String, volume: Float = 1.0f, pitch: Float = 1f) {
        val soundPath = SOUNDS_DIR.resolve(fileName)
        if (! Files.exists(soundPath)) return

        thread(start = true) {
            runCatching {
                playRawStream(Files.newInputStream(soundPath), volume, pitch)
            }.onFailure { it.printStackTrace() }
        }
    }

    fun playInternal(id: Identifier, volume: Float = 1.0f, pitch: Float = 1f) {
        val resource = mc.resourceManager.getResource(id)
        if (resource.isEmpty) return

        thread(start = true) {
            runCatching {
                playRawStream(resource.get().open(), volume, pitch)
            }.onFailure { it.printStackTrace() }
        }
    }

    private fun playRawStream(inputStream: InputStream, volume: Float = 1f, pitch: Float = 1f) {
        JOrbisAudioStream(inputStream).use { ogg ->
            val audioData = ogg.readAll()
            val format = if (ogg.format.channels == 1) AL10.AL_FORMAT_MONO16 else AL10.AL_FORMAT_STEREO16
            val sampleRate = ogg.format.sampleRate.toInt()

            val bufferId = AL10.alGenBuffers()
            AL10.alBufferData(bufferId, format, audioData, sampleRate)

            val sourceId = AL10.alGenSources()
            AL10.alSourcei(sourceId, AL10.AL_BUFFER, bufferId)

            AL10.alSourcef(sourceId, AL10.AL_GAIN, volume)
            AL10.alSourcef(sourceId, AL10.AL_PITCH, pitch)

            AL10.alSourcei(sourceId, AL10.AL_SOURCE_RELATIVE, AL10.AL_TRUE)
            AL10.alSource3f(sourceId, AL10.AL_POSITION, 0f, 0f, 0f)

            AL10.alSourcePlay(sourceId)

            while (AL10.alGetSourcei(sourceId, AL10.AL_SOURCE_STATE) == AL10.AL_PLAYING) {
                Thread.sleep(10)
            }

            AL10.alDeleteSources(sourceId)
            AL10.alDeleteBuffers(bufferId)
        }
    }

    private val MAP: Map<String, String> = mapOf(
        "ui.button.click" to "UI_BUTTON_CLICK",
        "ui.toast.challenge_complete" to "UI_TOAST_CHALLENGE_COMPLETE",
        "ui.toast.in" to "UI_TOAST_IN",
        "ui.toast.out" to "UI_TOAST_OUT",
        "entity.player.levelup" to "PLAYER_LEVELUP",
        "entity.experience_orb.pickup" to "XP_ORB_PICKUP",
        "block.note_block.banjo" to "NOTE_BANJO",
        "block.note_block.bass" to "NOTE_BASS",
        "block.note_block.basedrum" to "NOTE_BASEDRUM",
        "block.note_block.bell" to "NOTE_BELL",
        "block.note_block.bit" to "NOTE_BIT",
        "block.note_block.chime" to "NOTE_CHIME",
        "block.note_block.cow_bell" to "NOTE_COW_BELL",
        "block.note_block.didgeridoo" to "NOTE_DIDGERIDOO",
        "block.note_block.flute" to "NOTE_FLUTE",
        "block.note_block.guitar" to "NOTE_GUITAR",
        "block.note_block.harp" to "NOTE_HARP",
        "block.note_block.hat" to "NOTE_HAT",
        "block.note_block.iron_xylophone" to "NOTE_IRON_XYLOPHONE",
        "block.note_block.pling" to "NOTE_PLING",
        "block.note_block.snare" to "NOTE_SNARE",
        "block.note_block.xylophone" to "NOTE_XYLOPHONE",
        "block.note_block.imitate.zombie" to "NOTE_IMITATE_ZOMBIE",
        "block.note_block.imitate.skeleton" to "NOTE_IMITATE_SKELETON",
        "block.note_block.imitate.creeper" to "NOTE_IMITATE_CREEPER",
        "block.note_block.imitate.ender_dragon" to "NOTE_IMITATE_DRAGON",
        "block.note_block.imitate.wither_skeleton" to "NOTE_IMITATE_WITHER_SKELETON",
        "block.note_block.imitate.piglin" to "NOTE_IMITATE_PIGLIN",

        "block.ender_chest.open" to "ENDER_CHEST_OPEN",
        "block.ender_chest.close" to "ENDER_CHEST_CLOSE",
        "block.shulker_box.open" to "SHULKER_BOX_OPEN",
        "block.shulker_box.close" to "SHULKER_BOX_CLOSE",
        "block.barrel.open" to "BARREL_OPEN",
        "block.barrel.close" to "BARREL_CLOSE",
        "block.anvil.use" to "ANVIL_USE",
        "block.anvil.land" to "ANVIL_LAND",
        "block.anvil.destroy" to "ANVIL_DESTROY",
        "block.beacon.activate" to "BEACON_ACTIVATE",
        "block.beacon.deactivate" to "BEACON_DEACTIVATE",
        "block.enchantment_table.use" to "ENCHANT_TABLE_USE",
        "block.end_gateway.spawn" to "END_GATEWAY_SPAWN",
        "block.end_portal.spawn" to "END_PORTAL_SPAWN",
        "block.end_portal_frame.fill" to "END_PORTAL_FRAME_FILL",
        "block.fence_gate.open" to "FENCE_GATE_OPEN",
        "block.fence_gate.close" to "FENCE_GATE_CLOSE",
        "block.fire.extinguish" to "FIRE_EXTINGUISH",
        "block.respawn_anchor.charge" to "RESPAWN_ANCHOR_CHARGE",
        "block.respawn_anchor.deplete" to "RESPAWN_ANCHOR_DEPLETE",
        "block.respawn_anchor.set_spawn" to "RESPAWN_ANCHOR_SET_SPAWN",
        "block.sand.break" to "SAND_BREAK",
        "block.slime_block.hit" to "SLIME_HIT",
        "block.slime_block.place" to "SLIME_PLACE",
        "block.snow.break" to "SNOW_BREAK",
        "block.soul_sand.break" to "SOUL_SAND_BREAK",
        "block.stone.break" to "STONE_BREAK",
        "block.stone.hit" to "STONE_HIT",
        "block.stone.place" to "STONE_PLACE",
        "block.stone_button.click_off" to "STONE_BUTTON_OFF",
        "block.stone_button.click_on" to "STONE_BUTTON_ON",
        "block.stone_pressure_plate.click_off" to "STONE_PRESSURE_PLATE_OFF",
        "block.stone_pressure_plate.click_on" to "STONE_PRESSURE_PLATE_ON",
        "block.tripwire.attach" to "TRIPWIRE_ATTACH",
        "block.tripwire.click_off" to "TRIPWIRE_OFF",
        "block.tripwire.click_on" to "TRIPWIRE_ON",
        "block.tripwire.detach" to "TRIPWIRE_DETACH",
        "block.wood.break" to "WOOD_BREAK",
        "block.wood.hit" to "WOOD_HIT",
        "block.wood.place" to "WOOD_PLACE",
        "block.wooden_button.click_off" to "WOOD_BUTTON_OFF",
        "block.wooden_button.click_on" to "WOOD_BUTTON_ON",
        "block.wooden_door.close" to "WOOD_DOOR_CLOSE",
        "block.wooden_door.open" to "WOOD_DOOR_OPEN",
        "block.wooden_pressure_plate.click_off" to "WOOD_PRESSURE_PLATE_OFF",
        "block.wooden_pressure_plate.click_on" to "WOOD_PRESSURE_PLATE_ON",
        "block.wooden_trapdoor.close" to "WOOD_TRAPDOOR_CLOSE",
        "block.wooden_trapdoor.open" to "WOOD_TRAPDOOR_OPEN",
        "block.wool.break" to "WOOL_BREAK",
        "block.wool.hit" to "WOOL_HIT",
        "block.wool.place" to "WOOL_PLACE",

        "item.axe.strip" to "AXE_STRIP",
        "item.bone_meal.use" to "BONE_MEAL_USE",
        "item.book.page_turn" to "BOOK_PAGE_TURN",
        "item.book.put" to "BOOK_PUT",
        "item.bottle.empty" to "BOTTLE_EMPTY",
        "item.bottle.fill" to "BOTTLE_FILL",
        "item.bottle.fill_dragonbreath" to "BOTTLE_FILL_DRAGONBREATH",
        "item.bucket.empty" to "BUCKET_EMPTY",
        "item.bucket.empty_axolotl" to "BUCKET_EMPTY_AXOLOTL",
        "item.bucket.empty_fish" to "BUCKET_EMPTY_FISH",
        "item.bucket.empty_lava" to "BUCKET_EMPTY_LAVA",
        "item.bucket.fill" to "BUCKET_FILL",
        "item.bucket.fill_axolotl" to "BUCKET_FILL_AXOLOTL",
        "item.bucket.fill_fish" to "BUCKET_FILL_FISH",
        "item.bucket.fill_lava" to "BUCKET_FILL_LAVA",
        "item.chorus_fruit.teleport" to "CHORUS_FRUIT_TELEPORT",
        "item.crossbow.hit" to "CROSSBOW_HIT",
        "item.crossbow.loading_end" to "CROSSBOW_LOAD_END",
        "item.crossbow.loading_middle" to "CROSSBOW_LOAD_MIDDLE",
        "item.crossbow.loading_start" to "CROSSBOW_LOAD_START",
        "item.crossbow.quick_charge_1" to "CROSSBOW_QUICK_CHARGE_1",
        "item.crossbow.quick_charge_2" to "CROSSBOW_QUICK_CHARGE_2",
        "item.crossbow.quick_charge_3" to "CROSSBOW_QUICK_CHARGE_3",
        "item.crossbow.shoot" to "CROSSBOW_SHOOT",
        "item.crop.plant" to "CROP_PLANT",
        "item.elytra.flying" to "ELYTRA_FLYING",
        "item.firecharge.use" to "FIRECHARGE_USE",
        "item.flintandsteel.use" to "FLINT_AND_STEEL_USE",
        "item.glow_ink_sac.use" to "GLOW_INK_SAC_USE",
        "item.hoe.till" to "HOE_TILL",
        "item.honey_bottle.drink" to "HONEY_DRINK",
        "item.ink_sac.use" to "INK_SAC_USE",
        "item.lodestone_compass.lock" to "LODESTONE_COMPASS_LOCK",
        "item.nether_wart.plant" to "NETHER_WART_PLANT",
        "item.shield.block" to "SHIELD_BLOCK",
        "item.shield.break" to "SHIELD_BREAK",
        "item.shovel.flatten" to "SHOVEL_FLATTEN",
        "item.sweet_berries.pick_from_bush" to "BERRIES_PICK",
        "item.totem.use" to "TOTEM_USE",
        "item.trident.hit" to "TRIDENT_HIT",
        "item.trident.hit_ground" to "TRIDENT_HIT_GROUND",
        "item.trident.return" to "TRIDENT_RETURN",
        "item.trident.riptide_1" to "TRIDENT_RIPTIDE_1",
        "item.trident.riptide_2" to "TRIDENT_RIPTIDE_2",
        "item.trident.riptide_3" to "TRIDENT_RIPTIDE_3",
        "item.trident.throw" to "TRIDENT_THROW",
        "item.trident.thunder" to "TRIDENT_THUNDER",

        "entity.blaze.burn" to "BLAZE_BURN",
        "entity.blaze.death" to "BLAZE_DEATH",
        "entity.blaze.hurt" to "BLAZE_HURT",
        "entity.blaze.shoot" to "BLAZE_SHOOT",
        "entity.creeper.death" to "CREEPER_DEATH",
        "entity.creeper.hurt" to "CREEPER_HURT",
        "entity.creeper.primed" to "CREEPER_PRIMED",
        "entity.drowned.death" to "DROWNED_DEATH",
        "entity.drowned.hurt" to "DROWNED_HURT",
        "entity.drowned.shoot" to "DROWNED_SHOOT",
        "entity.drowned.swim" to "DROWNED_SWIM",
        "entity.elder_guardian.curse" to "ELDER_GUARDIAN_CURSE",
        "entity.elder_guardian.death" to "ELDER_GUARDIAN_DEATH",
        "entity.elder_guardian.hurt" to "ELDER_GUARDIAN_HURT",
        "entity.ender_dragon.death" to "DRAGON_DEATH",
        "entity.ender_dragon.flap" to "DRAGON_FLAP",
        "entity.ender_dragon.growl" to "DRAGON_GROWL",
        "entity.ender_dragon.hurt" to "DRAGON_HURT",
        "entity.ender_dragon.shoot" to "DRAGON_SHOOT",
        "entity.enderman.death" to "ENDERMAN_DEATH",
        "entity.enderman.hurt" to "ENDERMAN_HURT",
        "entity.enderman.scream" to "ENDERMAN_SCREAM",
        "entity.enderman.stare" to "ENDERMAN_STARE",
        "entity.enderman.teleport" to "ENDERMAN_TELEPORT",
        "entity.endermite.death" to "ENDERMITE_DEATH",
        "entity.endermite.hurt" to "ENDERMITE_HURT",
        "entity.evoker.cast_spell" to "EVOKER_CAST",
        "entity.evoker.celebrate" to "EVOKER_CELEBRATE",
        "entity.evoker.death" to "EVOKER_DEATH",
        "entity.evoker.hurt" to "EVOKER_HURT",
        "entity.evoker.prepare_attack" to "EVOKER_PREPARE_ATTACK",
        "entity.evoker.prepare_summon" to "EVOKER_PREPARE_SUMMON",
        "entity.evoker.prepare_wololo" to "EVOKER_PREPARE_WOLOLO",
        "entity.evoker_fangs.attack" to "EVOKER_FANGS_ATTACK",
        "entity.ghast.death" to "GHAST_DEATH",
        "entity.ghast.hurt" to "GHAST_HURT",
        "entity.ghast.scream" to "GHAST_SCREAM",
        "entity.ghast.shoot" to "GHAST_SHOOT",
        "entity.ghast.warn" to "GHAST_WARN",
        "entity.guardian.attack" to "GUARDIAN_ATTACK",
        "entity.guardian.death" to "GUARDIAN_DEATH",
        "entity.guardian.flop" to "GUARDIAN_FLOP",
        "entity.guardian.hurt" to "GUARDIAN_HURT",
        "entity.hoglin.angry" to "HOGLIN_ANGRY",
        "entity.hoglin.attack" to "HOGLIN_ATTACK",
        "entity.hoglin.death" to "HOGLIN_DEATH",
        "entity.hoglin.hurt" to "HOGLIN_HURT",
        "entity.husk.death" to "HUSK_DEATH",
        "entity.husk.hurt" to "HUSK_HURT",
        "entity.magma_cube.death" to "MAGMA_CUBE_DEATH",
        "entity.magma_cube.hurt" to "MAGMA_CUBE_HURT",
        "entity.magma_cube.jump" to "MAGMA_CUBE_JUMP",
        "entity.magma_cube.squish" to "MAGMA_CUBE_SQUISH",
        "entity.phantom.bite" to "PHANTOM_BITE",
        "entity.phantom.death" to "PHANTOM_DEATH",
        "entity.phantom.flap" to "PHANTOM_FLAP",
        "entity.phantom.hurt" to "PHANTOM_HURT",
        "entity.phantom.swoop" to "PHANTOM_SWOOP",
        "entity.piglin.admire_item" to "PIGLIN_ADMIRE",
        "entity.piglin.angry" to "PIGLIN_ANGRY",
        "entity.piglin.celebrate" to "PIGLIN_CELEBRATE",
        "entity.piglin.death" to "PIGLIN_DEATH",
        "entity.piglin.hurt" to "PIGLIN_HURT",
        "entity.piglin.jealous" to "PIGLIN_JEALOUS",
        "entity.piglin.retreat" to "PIGLIN_RETREAT",
        "entity.piglin_brute.angry" to "PIGLIN_BRUTE_ANGRY",
        "entity.piglin_brute.death" to "PIGLIN_BRUTE_DEATH",
        "entity.piglin_brute.hurt" to "PIGLIN_BRUTE_HURT",
        "entity.pillager.celebrate" to "PILLAGER_CELEBRATE",
        "entity.pillager.death" to "PILLAGER_DEATH",
        "entity.pillager.hurt" to "PILLAGER_HURT",
        "entity.ravager.attack" to "RAVAGER_ATTACK",
        "entity.ravager.celebrate" to "RAVAGER_CELEBRATE",
        "entity.ravager.death" to "RAVAGER_DEATH",
        "entity.ravager.hurt" to "RAVAGER_HURT",
        "entity.ravager.roar" to "RAVAGER_ROAR",
        "entity.ravager.stunned" to "RAVAGER_STUNNED",
        "entity.shulker.close" to "SHULKER_CLOSE",
        "entity.shulker.death" to "SHULKER_DEATH",
        "entity.shulker.hurt" to "SHULKER_HURT",
        "entity.shulker.hurt_closed" to "SHULKER_HURT_CLOSED",
        "entity.shulker.open" to "SHULKER_OPEN",
        "entity.shulker.shoot" to "SHULKER_SHOOT",
        "entity.shulker.teleport" to "SHULKER_TELEPORT",
        "entity.shulker_bullet.hit" to "SHULKER_BULLET_HIT",
        "entity.shulker_bullet.hurt" to "SHULKER_BULLET_HURT",
        "entity.silverfish.death" to "SILVERFISH_DEATH",
        "entity.silverfish.hurt" to "SILVERFISH_HURT",
        "entity.skeleton.death" to "SKELETON_DEATH",
        "entity.skeleton.hurt" to "SKELETON_HURT",
        "entity.skeleton.shoot" to "SKELETON_SHOOT",
        "entity.slime.attack" to "SLIME_ATTACK",
        "entity.slime.death" to "SLIME_DEATH",
        "entity.slime.hurt" to "SLIME_HURT",
        "entity.slime.jump" to "SLIME_JUMP",
        "entity.slime.squish" to "SLIME_SQUISH",
        "entity.spider.death" to "SPIDER_DEATH",
        "entity.spider.hurt" to "SPIDER_HURT",
        "entity.stray.death" to "STRAY_DEATH",
        "entity.stray.hurt" to "STRAY_HURT",
        "entity.vex.charge" to "VEX_CHARGE",
        "entity.vex.death" to "VEX_DEATH",
        "entity.vex.hurt" to "VEX_HURT",
        "entity.vindicator.celebrate" to "VINDICATOR_CELEBRATE",
        "entity.vindicator.death" to "VINDICATOR_DEATH",
        "entity.vindicator.hurt" to "VINDICATOR_HURT",
        "entity.warden.agitated" to "WARDEN_AGITATED",
        "entity.warden.angry" to "WARDEN_ANGRY",
        "entity.warden.attack_impact" to "WARDEN_ATTACK",
        "entity.warden.death" to "WARDEN_DEATH",
        "entity.warden.dig" to "WARDEN_DIG",
        "entity.warden.emerge" to "WARDEN_EMERGE",
        "entity.warden.heartbeat" to "WARDEN_HEARTBEAT",
        "entity.warden.hurt" to "WARDEN_HURT",
        "entity.warden.listening" to "WARDEN_LISTENING",
        "entity.warden.listening_angry" to "WARDEN_LISTENING_ANGRY",
        "entity.warden.nearby_close" to "WARDEN_NEARBY_CLOSE",
        "entity.warden.nearby_closer" to "WARDEN_NEARBY_CLOSER",
        "entity.warden.nearby_closest" to "WARDEN_NEARBY_CLOSEST",
        "entity.warden.roar" to "WARDEN_ROAR",
        "entity.warden.sniff" to "WARDEN_SNIFF",
        "entity.warden.sonic_boom" to "WARDEN_SONIC_BOOM",
        "entity.warden.tendril_clicks" to "WARDEN_TENDRIL",
        "entity.witch.celebrate" to "WITCH_CELEBRATE",
        "entity.witch.death" to "WITCH_DEATH",
        "entity.witch.drink" to "WITCH_DRINK",
        "entity.witch.hurt" to "WITCH_HURT",
        "entity.witch.throw" to "WITCH_THROW",
        "entity.wither.break_block" to "WITHER_BREAK_BLOCK",
        "entity.wither.death" to "WITHER_DEATH",
        "entity.wither.hurt" to "WITHER_HURT",
        "entity.wither.shoot" to "WITHER_SHOOT",
        "entity.wither.spawn" to "WITHER_SPAWN",
        "entity.wither_skeleton.death" to "WITHER_SKELETON_DEATH",
        "entity.wither_skeleton.hurt" to "WITHER_SKELETON_HURT",
        "entity.zoglin.angry" to "ZOGLIN_ANGRY",
        "entity.zoglin.attack" to "ZOGLIN_ATTACK",
        "entity.zoglin.death" to "ZOGLIN_DEATH",
        "entity.zoglin.hurt" to "ZOGLIN_HURT",
        "entity.zombie.attack_wooden_door" to "ZOMBIE_ATTACK_DOOR",
        "entity.zombie.break_wooden_door" to "ZOMBIE_BREAK_DOOR",
        "entity.zombie.converted_to_drowned" to "ZOMBIE_CONVERT_DROWNED",
        "entity.zombie.death" to "ZOMBIE_DEATH",
        "entity.zombie.destroy_egg" to "ZOMBIE_DESTROY_EGG",
        "entity.zombie.hurt" to "ZOMBIE_HURT",
        "entity.zombie.infect" to "ZOMBIE_INFECT",
        "entity.zombie_villager.converted" to "ZOMBIE_VILLAGER_CONVERTED",
        "entity.zombie_villager.cure" to "ZOMBIE_VILLAGER_CURE",
        "entity.zombie_villager.death" to "ZOMBIE_VILLAGER_DEATH",
        "entity.zombie_villager.hurt" to "ZOMBIE_VILLAGER_HURT",
        "entity.zombified_piglin.angry" to "ZOMBIFIED_PIGLIN_ANGRY",
        "entity.zombified_piglin.death" to "ZOMBIFIED_PIGLIN_DEATH",
        "entity.zombified_piglin.hurt" to "ZOMBIFIED_PIGLIN_HURT",

        "entity.axolotl.attack" to "AXOLOTL_ATTACK",
        "entity.axolotl.death" to "AXOLOTL_DEATH",
        "entity.axolotl.hurt" to "AXOLOTL_HURT",
        "entity.axolotl.idle_air" to "AXOLOTL_IDLE_AIR",
        "entity.axolotl.idle_water" to "AXOLOTL_IDLE_WATER",
        "entity.axolotl.splash" to "AXOLOTL_SPLASH",
        "entity.axolotl.swim" to "AXOLOTL_SWIM",
        "entity.bat.death" to "BAT_DEATH",
        "entity.bat.hurt" to "BAT_HURT",
        "entity.bat.loop" to "BAT_LOOP",
        "entity.bat.takeoff" to "BAT_TAKEOFF",
        "entity.bee.death" to "BEE_DEATH",
        "entity.bee.hurt" to "BEE_HURT",
        "entity.bee.loop" to "BEE_LOOP",
        "entity.bee.loop_aggressive" to "BEE_LOOP_AGGRESSIVE",
        "entity.bee.pollinate" to "BEE_POLLINATE",
        "entity.bee.sting" to "BEE_STING",
        "entity.cat.death" to "CAT_DEATH",
        "entity.cat.eat" to "CAT_EAT",
        "entity.cat.hiss" to "CAT_HISS",
        "entity.cat.hurt" to "CAT_HURT",
        "entity.cat.meow" to "CAT_MEOW",
        "entity.cat.purr" to "CAT_PURR",
        "entity.cat.purreow" to "CAT_PURREOW",
        "entity.chicken.death" to "CHICKEN_DEATH",
        "entity.chicken.egg" to "CHICKEN_EGG",
        "entity.chicken.hurt" to "CHICKEN_HURT",
        "entity.cod.death" to "COD_DEATH",
        "entity.cod.flop" to "COD_FLOP",
        "entity.cod.hurt" to "COD_HURT",
        "entity.cow.death" to "COW_DEATH",
        "entity.cow.hurt" to "COW_HURT",
        "entity.cow.milk" to "COW_MILK",
        "entity.dolphin.attack" to "DOLPHIN_ATTACK",
        "entity.dolphin.death" to "DOLPHIN_DEATH",
        "entity.dolphin.eat" to "DOLPHIN_EAT",
        "entity.dolphin.hurt" to "DOLPHIN_HURT",
        "entity.dolphin.jump" to "DOLPHIN_JUMP",
        "entity.dolphin.play" to "DOLPHIN_PLAY",
        "entity.dolphin.splash" to "DOLPHIN_SPLASH",
        "entity.dolphin.swim" to "DOLPHIN_SWIM",
        "entity.donkey.angry" to "DONKEY_ANGRY",
        "entity.donkey.chest" to "DONKEY_CHEST",
        "entity.donkey.death" to "DONKEY_DEATH",
        "entity.donkey.eat" to "DONKEY_EAT",
        "entity.donkey.hurt" to "DONKEY_HURT",
        "entity.fox.aggro" to "FOX_AGGRO",
        "entity.fox.bite" to "FOX_BITE",
        "entity.fox.death" to "FOX_DEATH",
        "entity.fox.eat" to "FOX_EAT",
        "entity.fox.hurt" to "FOX_HURT",
        "entity.fox.screech" to "FOX_SCREECH",
        "entity.fox.sleep" to "FOX_SLEEP",
        "entity.fox.sniff" to "FOX_SNIFF",
        "entity.fox.spit" to "FOX_SPIT",
        "entity.fox.teleport" to "FOX_TELEPORT",
        "entity.frog.death" to "FROG_DEATH",
        "entity.frog.eat" to "FROG_EAT",
        "entity.frog.hurt" to "FROG_HURT",
        "entity.frog.lay_spawn" to "FROG_LAY_SPAWN",
        "entity.frog.long_jump" to "FROG_LONG_JUMP",
        "entity.frog.tongue" to "FROG_TONGUE",
        "entity.goat.death" to "GOAT_DEATH",
        "entity.goat.eat" to "GOAT_EAT",
        "entity.goat.hurt" to "GOAT_HURT",
        "entity.goat.long_jump" to "GOAT_LONG_JUMP",
        "entity.goat.milk" to "GOAT_MILK",
        "entity.goat.prepare_ram" to "GOAT_PREPARE_RAM",
        "entity.goat.ram_impact" to "GOAT_RAM_IMPACT",
        "entity.goat.screaming.death" to "GOAT_SCREAMING_DEATH",
        "entity.goat.screaming.eat" to "GOAT_SCREAMING_EAT",
        "entity.goat.screaming.hurt" to "GOAT_SCREAMING_HURT",
        "entity.goat.screaming.milk" to "GOAT_SCREAMING_MILK",
        "entity.goat.screaming.prepare_ram" to "GOAT_SCREAMING_PREPARE_RAM",
        "entity.goat.screaming.ram_impact" to "GOAT_SCREAMING_RAM_IMPACT",
        "entity.iron_golem.attack" to "IRON_GOLEM_ATTACK",
        "entity.iron_golem.damage" to "IRON_GOLEM_DAMAGE",
        "entity.iron_golem.death" to "IRON_GOLEM_DEATH",
        "entity.iron_golem.hurt" to "IRON_GOLEM_HURT",
        "entity.iron_golem.repair" to "IRON_GOLEM_REPAIR",
        "entity.llama.angry" to "LLAMA_ANGRY",
        "entity.llama.chest" to "LLAMA_CHEST",
        "entity.llama.death" to "LLAMA_DEATH",
        "entity.llama.eat" to "LLAMA_EAT",
        "entity.llama.hurt" to "LLAMA_HURT",
        "entity.llama.spit" to "LLAMA_SPIT",
        "entity.llama.swag" to "LLAMA_SWAG",
        "entity.mooshroom.convert" to "MOOSHROOM_CONVERT",
        "entity.mooshroom.eat" to "MOOSHROOM_EAT",
        "entity.mooshroom.milk" to "MOOSHROOM_MILK",
        "entity.mooshroom.shear" to "MOOSHROOM_SHEAR",
        "entity.mooshroom.suspicious_milk" to "MOOSHROOM_SUS_MILK",
        "entity.mule.angry" to "MULE_ANGRY",
        "entity.mule.chest" to "MULE_CHEST",
        "entity.mule.death" to "MULE_DEATH",
        "entity.mule.eat" to "MULE_EAT",
        "entity.mule.hurt" to "MULE_HURT",
        "entity.ocelot.death" to "OCELOT_DEATH",
        "entity.ocelot.hurt" to "OCELOT_HURT",
        "entity.panda.bite" to "PANDA_BITE",
        "entity.panda.cant_breed" to "PANDA_CANT_BREED",
        "entity.panda.death" to "PANDA_DEATH",
        "entity.panda.eat" to "PANDA_EAT",
        "entity.panda.hurt" to "PANDA_HURT",
        "entity.panda.pre_sneeze" to "PANDA_PRE_SNEEZE",
        "entity.panda.sneeze" to "PANDA_SNEEZE",
        "entity.pig.death" to "PIG_DEATH",
        "entity.pig.hurt" to "PIG_HURT",
        "entity.pig.saddle" to "PIG_SADDLE",
        "entity.polar_bear.death" to "POLAR_BEAR_DEATH",
        "entity.polar_bear.hurt" to "POLAR_BEAR_HURT",
        "entity.polar_bear.warning" to "POLAR_BEAR_WARNING",
        "entity.puffer_fish.blow_out" to "PUFFER_FISH_BLOW_OUT",
        "entity.puffer_fish.blow_up" to "PUFFER_FISH_BLOW_UP",
        "entity.puffer_fish.death" to "PUFFER_FISH_DEATH",
        "entity.puffer_fish.flop" to "PUFFER_FISH_FLOP",
        "entity.puffer_fish.hurt" to "PUFFER_FISH_HURT",
        "entity.puffer_fish.sting" to "PUFFER_FISH_STING",
        "entity.rabbit.attack" to "RABBIT_ATTACK",
        "entity.rabbit.death" to "RABBIT_DEATH",
        "entity.rabbit.hurt" to "RABBIT_HURT",
        "entity.rabbit.jump" to "RABBIT_JUMP",
        "entity.salmon.death" to "SALMON_DEATH",
        "entity.salmon.flop" to "SALMON_FLOP",
        "entity.salmon.hurt" to "SALMON_HURT",
        "entity.sheep.death" to "SHEEP_DEATH",
        "entity.sheep.hurt" to "SHEEP_HURT",
        "entity.sheep.shear" to "SHEEP_SHEAR",
        "entity.sniffer.death" to "SNIFFER_DEATH",
        "entity.sniffer.digging" to "SNIFFER_DIGGING",
        "entity.sniffer.digging_stop" to "SNIFFER_DIGGING_STOP",
        "entity.sniffer.drop_seed" to "SNIFFER_DROP_SEED",
        "entity.sniffer.eat" to "SNIFFER_EAT",
        "entity.sniffer.happy" to "SNIFFER_HAPPY",
        "entity.sniffer.hurt" to "SNIFFER_HURT",
        "entity.sniffer.idle" to "SNIFFER_IDLE",
        "entity.sniffer.scenting" to "SNIFFER_SCENTING",
        "entity.sniffer.searching" to "SNIFFER_SEARCHING",
        "entity.sniffer.sniffing" to "SNIFFER_SNIFFING",
        "entity.snow_golem.death" to "SNOW_GOLEM_DEATH",
        "entity.snow_golem.hurt" to "SNOW_GOLEM_HURT",
        "entity.snow_golem.shear" to "SNOW_GOLEM_SHEAR",
        "entity.snow_golem.shoot" to "SNOW_GOLEM_SHOOT",
        "entity.squid.death" to "SQUID_DEATH",
        "entity.squid.hurt" to "SQUID_HURT",
        "entity.squid.squirt" to "SQUID_SQUIRT",
        "entity.strider.death" to "STRIDER_DEATH",
        "entity.strider.eat" to "STRIDER_EAT",
        "entity.strider.happy" to "STRIDER_HAPPY",
        "entity.strider.hurt" to "STRIDER_HURT",
        "entity.strider.retreat" to "STRIDER_RETREAT",
        "entity.strider.saddle" to "STRIDER_SADDLE",
        "entity.tadpole.death" to "TADPOLE_DEATH",
        "entity.tadpole.flop" to "TADPOLE_FLOP",
        "entity.tadpole.grow_up" to "TADPOLE_GROW_UP",
        "entity.tadpole.hurt" to "TADPOLE_HURT",
        "entity.tropical_fish.death" to "TROPICAL_FISH_DEATH",
        "entity.tropical_fish.flop" to "TROPICAL_FISH_FLOP",
        "entity.tropical_fish.hurt" to "TROPICAL_FISH_HURT",
        "entity.turtle.death" to "TURTLE_DEATH",
        "entity.turtle.death_baby" to "TURTLE_DEATH_BABY",
        "entity.turtle.egg_break" to "TURTLE_EGG_BREAK",
        "entity.turtle.egg_crack" to "TURTLE_EGG_CRACK",
        "entity.turtle.egg_hatch" to "TURTLE_EGG_HATCH",
        "entity.turtle.hurt" to "TURTLE_HURT",
        "entity.turtle.hurt_baby" to "TURTLE_HURT_BABY",
        "entity.turtle.lay_egg" to "TURTLE_LAY_EGG",
        "entity.turtle.shamble" to "TURTLE_SHAMBLE",
        "entity.turtle.shamble_baby" to "TURTLE_SHAMBLE_BABY",
        "entity.turtle.swim" to "TURTLE_SWIM",
        "entity.villager.celebrate" to "VILLAGER_CELEBRATE",
        "entity.villager.death" to "VILLAGER_DEATH",
        "entity.villager.hurt" to "VILLAGER_HURT",
        "entity.villager.no" to "VILLAGER_NO",
        "entity.villager.trade" to "VILLAGER_TRADE",
        "entity.villager.work_armorer" to "VILLAGER_WORK_ARMORER",
        "entity.villager.work_butcher" to "VILLAGER_WORK_BUTCHER",
        "entity.villager.work_cartographer" to "VILLAGER_WORK_CARTOGRAPHER",
        "entity.villager.work_cleric" to "VILLAGER_WORK_CLERIC",
        "entity.villager.work_farmer" to "VILLAGER_WORK_FARMER",
        "entity.villager.work_fisherman" to "VILLAGER_WORK_FISHERMAN",
        "entity.villager.work_fletcher" to "VILLAGER_WORK_FLETCHER",
        "entity.villager.work_leatherworker" to "VILLAGER_WORK_LEATHERWORKER",
        "entity.villager.work_librarian" to "VILLAGER_WORK_LIBRARIAN",
        "entity.villager.work_mason" to "VILLAGER_WORK_MASON",
        "entity.villager.work_shepherd" to "VILLAGER_WORK_SHEPHERD",
        "entity.villager.work_toolsmith" to "VILLAGER_WORK_TOOLSMITH",
        "entity.villager.work_weaponsmith" to "VILLAGER_WORK_WEAPONSMITH",
        "entity.villager.yes" to "VILLAGER_YES",
        "entity.wolf.death" to "WOLF_DEATH",
        "entity.wolf.growl" to "WOLF_GROWL",
        "entity.wolf.howl" to "WOLF_HOWL",
        "entity.wolf.hurt" to "WOLF_HURT",
        "entity.wolf.pant" to "WOLF_PANT",
        "entity.wolf.shake" to "WOLF_SHAKE",
        "entity.wolf.whine" to "WOLF_WHINE",
    )

    val REVERSE_MAP: Map<Identifier, String> by lazy {
        val result = mutableMapOf<Identifier, String>()

        MAP.forEach { (path, prettyName) ->
            val location = Identifier.fromNamespaceAndPath("minecraft", path)
            result[location] = prettyName
        }

        result
    }
}