name: Build

on:
  pull_request:
    paths: &build-paths
      - ".gitattributes"
      - ".github/workflows/build.yml"
      - "buildSrc/**"
      - "gradle/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "gradlew"
      - "LICENSE"
      - "settings.gradle.kts"
  push:
    branches: ["26.1.2", "26.2"]
    paths: *build-paths

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build variants
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          show-progress: false
          sparse-checkout: |
            /buildSrc/
            /gradle/
            /src/
            /build.gradle.kts
            /gradle.properties
            /gradlew
            /LICENSE
            /settings.gradle.kts
          sparse-checkout-cone-mode: false

      - name: Set up JDK 25
        uses: actions/setup-java@v5.6.0
        with:
          java-version: "25"
          distribution: microsoft
          verify-signature: true

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6.2.0
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build legit and cheat variants
        run: ./gradlew build --build-cache

      - name: Upload legit JAR
        uses: actions/upload-artifact@v7.0.1
        with:
          path: build/libs/*-legit.jar
          if-no-files-found: error
          archive: false

      - name: Upload cheat JAR
        uses: actions/upload-artifact@v7.0.1
        with:
          path: build/libs/*-cheat.jar
          if-no-files-found: error
          archive: false
